#!/usr/bin/env bash

COMPOSER="docker-compose"

if [ "$#" -gt 0 ];then
	if [ "$1" == "npm" ];then
		shift 1
		$COMPOSER run --rm \
			-w /ntask-api \
			node \
			npm "$@"
	elif [ "$1" == "rs" ];then
		$COMPOSER down
		$COMPOSER up
        elif [ "$1" == "rsd" ];then
                $COMPOSER down
                $COMPOSER up -d
	else
		$COMPOSER "$@"
	fi
else
	$COMPOSER ps
fi
