#!/usr/bin/env bash

COMPOSER="docker-compose"

if [ "$#" -gt 0 ];then
	if [ "$1" == "npm" ];then
		shift 1
		$COMPOSER run --rm \
			-w /ntask-api \
			node \
			npm "$@"
	else
		$COMPOSER "$@"
	fi
else
	$COMPOSER ps
fi
